import type { RepoTraffic } from "./github-api";

function days(base: number, jitter: number, n = 14) {
  const out: { timestamp: string; count: number; uniques: number }[] = [];
  const start = new Date("2024-10-01T00:00:00Z");
  for (let i = 0; i < n; i++) {
    const d = new Date(start);
    d.setUTCDate(start.getUTCDate() + i);
    const count = Math.max(0, Math.round(base + Math.sin(i / 2) * jitter + (Math.random() - 0.5) * jitter));
    out.push({
      timestamp: d.toISOString(),
      count,
      uniques: Math.max(0, Math.round(count * (0.5 + Math.random() * 0.3))),
    });
  }
  return out;
}

export const DEMO_DATA: RepoTraffic[] = [
  {
    repository: "ameyac11/gitlytics",
    is_private: false,
    stars: 412,
    forks: 58,
    views: 8420,
    unique_visitors: 5120,
    clones: 940,
    unique_cloners: 610,
    top_referrer: "google.com",
    top_referrer_views: 1820,
    top_referrer_uniques: 1240,
    top_path: "/tree/main/docs",
    top_path_views: 940,
    top_path_uniques: 720,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(560, 180),
    _daily_clones: days(62, 30),
    _referrers: [
      { referrer: "google.com", count: 1820, uniques: 1240 },
      { referrer: "github.com", count: 1110, uniques: 880 },
      { referrer: "reddit.com", count: 640, uniques: 510 },
      { referrer: "news.ycombinator.com", count: 420, uniques: 360 },
      { referrer: "twitter.com", count: 280, uniques: 240 },
    ],
    _paths: [
      { path: "/tree/main/docs", title: "Documentation", count: 940, uniques: 720 },
      { path: "/", title: "gitlytics", count: 820, uniques: 640 },
      { path: "/blob/main/README.md", title: "README", count: 510, uniques: 420 },
      { path: "/releases", title: "Releases", count: 290, uniques: 230 },
    ],
  },
  {
    repository: "ameyac11/gitlytics-github-traffic-automation",
    is_private: false,
    stars: 248,
    forks: 31,
    views: 5230,
    unique_visitors: 3140,
    clones: 610,
    unique_cloners: 390,
    top_referrer: "github.com",
    top_referrer_views: 980,
    top_referrer_uniques: 760,
    top_path: "/",
    top_path_views: 720,
    top_path_uniques: 560,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(340, 120),
    _daily_clones: days(40, 18),
    _referrers: [
      { referrer: "github.com", count: 980, uniques: 760 },
      { referrer: "google.com", count: 720, uniques: 540 },
      { referrer: "dev.to", count: 310, uniques: 260 },
    ],
    _paths: [
      { path: "/", title: "awesome-cli", count: 720, uniques: 560 },
      { path: "/wiki", title: "Wiki", count: 340, uniques: 280 },
    ],
  },
  {
    repository: "ameyac11/data-pipeline",
    is_private: true,
    stars: 96,
    forks: 12,
    views: 2870,
    unique_visitors: 1680,
    clones: 320,
    unique_cloners: 210,
    top_referrer: "google.com",
    top_referrer_views: 540,
    top_referrer_uniques: 420,
    top_path: "/tree/main/src",
    top_path_views: 410,
    top_path_uniques: 320,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(190, 70),
    _daily_clones: days(21, 10),
    _referrers: [
      { referrer: "google.com", count: 540, uniques: 420 },
      { referrer: "github.com", count: 380, uniques: 300 },
    ],
    _paths: [{ path: "/tree/main/src", title: "Source", count: 410, uniques: 320 }],
  },
  {
    repository: "ameyac11/portfolio-site",
    is_private: false,
    stars: 64,
    forks: 9,
    views: 1940,
    unique_visitors: 1210,
    clones: 140,
    unique_cloners: 95,
    top_referrer: "linkedin.com",
    top_referrer_views: 410,
    top_referrer_uniques: 340,
    top_path: "/",
    top_path_views: 380,
    top_path_uniques: 300,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(130, 50),
    _daily_clones: days(9, 5),
    _referrers: [
      { referrer: "linkedin.com", count: 410, uniques: 340 },
      { referrer: "google.com", count: 290, uniques: 230 },
    ],
    _paths: [{ path: "/", title: "portfolio-site", count: 380, uniques: 300 }],
  },
  {
    repository: "ameyac11/ml-experiments",
    is_private: false,
    stars: 38,
    forks: 6,
    views: 1120,
    unique_visitors: 720,
    clones: 88,
    unique_cloners: 61,
    top_referrer: "kaggle.com",
    top_referrer_views: 220,
    top_referrer_uniques: 180,
    top_path: "/notebooks",
    top_path_views: 180,
    top_path_uniques: 150,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(78, 30),
    _daily_clones: days(6, 4),
    _referrers: [{ referrer: "kaggle.com", count: 220, uniques: 180 }],
    _paths: [{ path: "/notebooks", title: "Notebooks", count: 180, uniques: 150 }],
  },
  {
    repository: "ameyac11/snippets",
    is_private: false,
    stars: 19,
    forks: 3,
    views: 640,
    unique_visitors: 410,
    clones: 52,
    unique_cloners: 38,
    top_referrer: "google.com",
    top_referrer_views: 140,
    top_referrer_uniques: 80,
    top_path: "/",
    top_path_views: 120,
    top_path_uniques: 90,
    date: "2024-10-15 12:00 UTC",
    _daily_views: days(44, 18),
    _daily_clones: days(4, 3),
    _referrers: [],
    _paths: [],
  },
];
